# Generated by Django 5.0 on 2024-01-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEG_REC', '0005_alter_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Recipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
